# Generated by Django 2.2.1 on 2019-05-13 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190513_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='univ_detail',
            name='id',
        ),
        migrations.AddField(
            model_name='univ_detail',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
