# Generated by Django 2.2.1 on 2019-05-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190513_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=31, verbose_name='親')),
                ('child', models.CharField(max_length=31, verbose_name='子')),
            ],
        ),
    ]
