# Generated by Django 2.2.1 on 2019-05-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190513_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='subject_name',
            field=models.CharField(default=1, max_length=31, verbose_name='学科名'),
            preserve_default=False,
        ),
    ]
