# Generated by Django 2.2.1 on 2019-05-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190514_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='univ',
            field=models.CharField(default=1, max_length=31, verbose_name='大学名'),
            preserve_default=False,
        ),
    ]
